### ISSUE TITLE
Lifetime flexibility

### ISSUE THREAD

**Issue by ejmount** [NfNitLoop/pipeliner#2]
Why does `PipelineBuilder::map` require a callable that has a lifetime of `static`? Is there a problem with passing through the lifetime of whatever callable is provided? (i.e. the callable has to live at least as long as the iterator does so that there's no attempt to call a deallocated object) I ask because I was attempting to use this in a context where the callable was a closure, which I believe is sound because I reduce the iterator before the caller to `map` exits, so there is no possibility of calling a deallocated function.

**Comment by NfNitLoop** [comment]
To be honest, it's that way because I wrote this when I was a bit of a Rust newbie and went with the most straightforward solution -- where values are passed through subsequent channels, to be returned via a final iterator.

I've had the idea in the back of my mind to revisit and make the lifetimes more flexible. But I'm not sure I can without further complicating the API.

Now that I know there's interest here, I may make a weekend project out of this.  (Sorry for the delay. Apparently GitHub doesn't make you watch your own repos by default. Wat!? So I only just now noticed people had opened a couple issues.)

**Comment by NfNitLoop** [comment]
I re-read what you wrote, @ejmount -- you're wanting to be able to use a *callable* that isn't static, not pass non-static values.

I did some reading on this and I'm not sure if this is possible to do with safe code. The callable you pass in to `map()` will be referenced by multiple threads behind the scenes, and the type system can't guarantee that those threads will have released their references at any certain point.

Even with something like crossbeam's scoped threads, we're out of luck because the scope is only accessible during the lifetime of the [crossbeam::scope()](https://docs.rs/crossbeam/0.3.0/crossbeam/fn.scope.html) call, which wouldn't let us have this simple API that works on any iterator.

I'm open to suggestions or pull requests here if I'm mistaken, though!

In the meantime, if you're just trying to use a closure for your map() function that references some local variables, you can make the closure `'static` by using the `move` keyword with it.

**Comment by NfNitLoop** [comment]
Closing as "won't fix" because I don't see a way how. Happy to re-open if someone has suggestions here that don't involve unsafe code.
